#!/usr/bin/env python3
# ./cradle --image-name registry.com/namespace/rhel --image-tag 8.2 --cradle-image scratch --image-file ./images/rhel-8.2.x86_64.qcow2

import os
import gzip
import shutil
import tempfile
import time
import argparse
import subprocess
import urllib.request

# Define Mandatory & Optional CLI Flags
parser = argparse.ArgumentParser(
    description="KubeVirt Image Cradle Builder to generate OpenShift Virtualization compatible qcow2 import images"
)
parser.add_argument(
    "--image-name",
    default="localhost/cradle",
    help="Name of cradle image",
    metavar="registry.com/namespace/image-name",
    required=False,
)
parser.add_argument(
    "--image-tag",
    default="",
    help="Image tag",
    metavar="IMAGE_TAG",
    required=True,
)
parser.add_argument(
    "--cradle-image",
    help="Name of cradle image",
    default="quay.io/containercraft/ubi:base",
    required=False,
)
parser.add_argument(
    "--image-file",
    help="qcow image path",
    metavar="/global/path/to/image.qcow2",
    default="",
    required=False,
)
parser.add_argument(
    "--tmpdir",
    help="temporary staging path",
    metavar="./path/to/scratch/space",
    default="./tmp",
    required=False,
)


# Build Disk Image Cradle Container
def build_cradle(from_image: str, name: str, tag: str, tmpdir: str):
    def buildah(*cmd) -> str:
        run_cmd = ["buildah", *cmd]
        str_cmd = " ".join(run_cmd).replace("\n", "")
        print(f">>    {str_cmd}")
        return subprocess.run(
            run_cmd,
            env=dict(os.environ, STORAGE_DRIVER="overlay"),
            capture_output=True,
            text=True,
            check=True,
            cwd=tmpdir,
        ).stdout

    print(f">> Building Container Disk Image: {name}:{tag}")
    tmp_image = buildah("from", from_image).replace('\n', '')
    buildah("add", tmp_image, "./rootfs", "/")
    buildah("commit", tmp_image, name)
    buildah("tag", name, f"{name}:{tag}")


def main() -> int:
    args = parser.parse_args()

    with tempfile.TemporaryDirectory(prefix="cradle") as tmpdir:
        staging_dir = tmpdir + "/rootfs/disk"
        qcow2_staging_path = staging_dir + "/image.qcow2"

        os.makedirs(staging_dir)
        if args.image_file != "":
            print(">> Staging Image File: " + args.image_file)
            shutil.copy(args.image_file, qcow2_staging_path)

        build_cradle(args.cradle_image, args.image_name, args.image_tag, tmpdir)

    return 0


if __name__ == "__main__":
    exit(main())
