---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: testvm
  labels:
    test: kmi
    kubevirt.io/flavor: default-features
spec:
  nodeSelector:
    test: kmi
  domain:
    devices:
      disks:
        - name: containerdisk
          bootOrder: 1
          disk:
            bus: virtio
        - name: cloudinitdisk
          disk:
            bus: virtio
  hostname: testvm
  terminationGracePeriodSeconds: 0
  accessCredentials:
    - sshPublicKey:
        source:
          secret:
            secretName: kargo-sshpubkey-kc2user
        propagationMethod:
          qemuGuestAgent:
            users:
              - kc2user
  volumes:
    - name: containerdisk
      containerDisk:
        image: docker.io/containercraft/rhcos:4.9-dev
        imagePullPolicy: Always
    - name: cloudinitdisk
      cloudInitConfigDrive:
        userData: |-
          {
            "ignition": {
              "version": "3.2.0"
            },
            "passwd": {
              "users": [
                {
                  "groups": ["adm", "sudo", "wheel", "systemd-journal"],
                  "name": "kc2user",
                  "passwordHash": "$6$PNObhlqtbaVu81X9$NDUNjKfoCYIsq.fUvoDMYr62ijGUWiNgUpY.2zCl72JCxbg1plohB2pVHH1H7NUcj24S9xjLBUVt4/rbAkagq/"
                }
              ]
            }
          }
