version: '2.1'
orbs:
  slack: circleci/slack@4.5.0

aliases:

  debian-flavors: &_debian-flavors
    - debian-10
    - debian-11

  fedora-flavors: &_fedora-flavors
    - fedora-34
    - fedora-35

  opensuse-flavors: &_opensuse-flavors
    - opensuse-leap
    - opensuse-tumbleweed

  ubuntu-flavors: &_ubuntu-flavors
    - ubuntu-18.04
#    - ubuntu-20.04
#    - ubuntu-21.10

  cache-key: &_cache-key
    # cache key contains three different ways to bust the cache:
    # 1. the checksum of the flavor's sha256sum changes (written out in the workflow)
    # 2. the flavor's virt.sysprep file changes
    # 3. the number on the end (if all else fails, increase the number)
    key: << parameters.flavor >>-<< parameters.arch >>-{{ checksum "kmi/<< parameters.flavor >>/sha256sum-<< parameters.arch >>.txt" }}-{{ checksum "kmi/<< parameters.flavor >>/virt.sysprep" }}-1

#################################################################################
# Job Scheduler
workflows:

  build-and-publish-dev:
    jobs:
#      # Start Fedora #
#      - customize:
#          name: customize-<< matrix.flavor >>-<< matrix.arch >>
#          matrix:
#            parameters:
#              flavor: *_fedora-flavors
#              arch: [amd64, arm64]

#      - cradle:
#          requires:
#            - customize-<< matrix.flavor >>-amd64
#            - customize-<< matrix.flavor >>-arm64
#          name: cradle-<< matrix.flavor >>
#          matrix:
#            parameters:
#              flavor: *_fedora-flavors

#      - trigger-tests:
#          requires:
#            - cradle-<< matrix.flavor >>
#          name: trigger-<< matrix.flavor >>-promotion
#          matrix:
#            parameters:
#              flavor: *_fedora-flavors
#      # End Fedora #

#      # Start Ubuntu #
#      - customize:
#          name: customize-<< matrix.flavor >>-<< matrix.arch >>
#          matrix:
#            parameters:
#              flavor: *_ubuntu-flavors
#              arch: [amd64, arm64]

#      - cradle:
#          requires:
#            - customize-<< matrix.flavor >>-amd64
#            - customize-<< matrix.flavor >>-arm64
#          name: cradle-<< matrix.flavor >>
#          matrix:
#            parameters:
#              flavor: *_ubuntu-flavors

#      - trigger-tests:
#          requires:
#            - cradle-<< matrix.flavor >>
#          name: trigger-<< matrix.flavor >>-promotion
#          matrix:
#            parameters:
#              flavor: *_ubuntu-flavors
#      # End Ubuntu #

#      # Start Debian #
#      - customize:
#          name: customize-<< matrix.flavor >>-<< matrix.arch >>
#          matrix:
#            parameters:
#              flavor: *_debian-flavors
#              arch: [amd64, arm64]

#      - cradle:
#          requires:
#            - customize-<< matrix.flavor >>-amd64
#            - customize-<< matrix.flavor >>-arm64
#          name: cradle-<< matrix.flavor >>
#          matrix:
#            parameters:
#              flavor: *_debian-flavors

#      - trigger-tests:
#          requires:
#            - cradle-<< matrix.flavor >>
#          name: trigger-<< matrix.flavor >>-promotion
#          matrix:
#            parameters:
#              flavor: *_debian-flavors
#     # End Debian #

#     # Start openSUSE #
      - customize:
          name: customize-<< matrix.flavor >>-<< matrix.arch >>
          matrix:
            parameters:
              flavor: *_opensuse-flavors
              arch: [amd64]

      - cradle:
          requires:
            - customize-<< matrix.flavor >>-amd64
          name: cradle-<< matrix.flavor >>
          matrix:
            parameters:
              flavor: *_opensuse-flavors

      - trigger-tests:
          requires:
            - cradle-<< matrix.flavor >>
          name: trigger-<< matrix.flavor >>-promotion
          matrix:
            parameters:
              flavor: *_opensuse-flavors
#     # End openSUSE #

#################################################################################
# Reuseable Jobs
jobs:

  # Download & Prepare qcow2 image(s)
  customize:
    parameters:
      flavor:
        type: string
      arch:
        type: string
    executor: << parameters.arch >>
    environment:
      FLAVOR: << parameters.flavor >>
      ARCH: << parameters.arch >>
    steps:
      - checkout
      - prepare-qcow2:
          flavor: << parameters.flavor >>
          arch: << parameters.arch >>
      - ops-notify-err

  # Containerize qcow2 image(s)
  cradle:
    parameters:
      flavor:
        type: string
    executor: amd64
    environment:
      FLAVOR: << parameters.flavor >>
    steps:
      - checkout
      - cradle-qcow2:
          flavor: << parameters.flavor >>
      - ops-notify-err

  trigger-tests:
    executor: amd64
    parameters:
      flavor:
        type: string
    steps:
      - trigger-gha-test:
          flavor: << parameters.flavor >>
      - ops-notify-err

#################################################################################
# Reuseable Commands
commands:
  trigger-gha-test:
    description: "Tests: Trigger GHA Test Workflow"
    parameters:
      flavor:
        type: string
    steps:
      - run:
          name: Trigger GitHub Actions E2E test and promote workflow
          command: |
            set -x
            curl \
              --fail \
              --request POST \
              --header "Authorization: token $GITHUB_ACTIONS_PAT" \
              --header "Accept: application/vnd.github.everest-preview+json" \
              --data-raw '{"ref":"<< pipeline.git.branch >>", "inputs": {"flavor": "<< parameters.flavor >>"}' \
              https://api.github.com/repos/containercraft/kmi/actions/workflows/test.yml/dispatches
 
  buildx-bake:
    description: "Runner: Execute Docker Buildx"
    parameters:
      bake_file:
        type: string
        default: bake.hcl
      target:
        type: string
    steps:
      - run:
          command: |
            docker buildx bake \
              -f << parameters.bake_file >> \
              --push \
              --progress plain \
              << parameters.target >>

  # CMD: Configure Docker BuildX
  enable-buildx:
    description: "Runner: Configure Docker Buildx Environment"
    parameters:
      buildkit_version:
        type: string
        default: latest
    steps:
      - run:
          name: Install All Emulators
          command: |
            docker run --privileged --rm tonistiigi/binfmt --install arm64
      - run:
          name: Create builder with buildkit << parameters.buildkit_version >>
          command: |
            docker buildx ls \
              | grep "build-<< parameters.buildkit_version >>" \
              || docker buildx create --use \
              --name build-<< parameters.buildkit_version >> \
              --driver docker-container \
              --driver-opt image=moby/buildkit:<< parameters.buildkit_version >>,network=host
      - run:
          name: Set builder
          command: docker buildx use --default build-<< parameters.buildkit_version >>
      - run:
          name: Start up buildx and inspect
          command: docker buildx inspect --bootstrap
      - run:
          name: Login to dockerhub
          command: echo ${DOCKERHUB_PASSWORD} | docker login -u ${DOCKERHUB_USERNAME} --password-stdin
      - ops-notify-err

  prepare-qcow2:
    description: "Qcow2 Image: Download and Customize"
    parameters:
      flavor:
        type: string
      arch:
        type: string
    steps:
      - run:
          command: |
            echo $(jq -r .${FLAVOR%%-*}.\"${FLAVOR##*-}\".${ARCH}.sha256sum index.json) > kmi/${FLAVOR}/sha256sum-${ARCH}.txt

      - restore_cache:
          <<: *_cache-key

      - run:
          name: Customize image
          no_output_timeout: 90m
          command: |

            FLAVOR=<< parameters.flavor >>
            ARCH=<< parameters.arch >>

            # Check for && confirm cached customized image present || If not
            # present then customize and cache
            if [[ ! -f ${FLAVOR}-${ARCH}.qcow2 ]]; then
              set -ex

              sudo apt-get update
              sudo apt-get install -y \
                jq curl qemu-user libguestfs-tools qemu-user-static

              bash hack/customize.sh ${FLAVOR} ${ARCH}
            else
              echo "Detected cached disk image ... continuing"
            fi

      - save_cache:
          <<: *_cache-key
          paths:
            - << parameters.flavor >>-<< parameters.arch >>.qcow2

      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - << parameters.flavor >>-<< parameters.arch >>.qcow2

  cradle-qcow2:
    description: "Qcow2 Image: Download and Customize"
    parameters:
      flavor:
        type: string
    steps:
      - attach_workspace:
          at: /home/circleci/project/images

      - run:
          command: ls -lah images/

      - enable-buildx
      - buildx-bake:
          target: << parameters.flavor >>

  # CMD: Slack Notify if ERR
  ops-notify-err:
    description: Alert Ops if Abort Failures Occur
    steps:
      - slack/notify:
          event: fail
          channel: ops-kargo
          template: basic_fail_1

#################################################################################
# Workflow Runner Instances
executors:

  # ARM64 Runner
  arm64:
    machine:
      enabled: true
      image: ubuntu-2004:202111-01
    environment:
      DOCKER_CLI_EXPERIMENTAL: enabled
    resource_class: arm.medium

  # AMD64 Runner
  amd64:
    machine:
      enabled: true
      image: ubuntu-2004:202111-01
    environment:
      DOCKER_CLI_EXPERIMENTAL: enabled
    resource_class: medium
