version: '2.1'
orbs:
  slack: circleci/slack@4.5.0

aliases:
  - &platform_parameter
      platform:
        type: enum
        enum: [amd64, arm64]
        default: amd64

#################################################################################
# Job Scheduler
workflows:
  build-and-cache:
    jobs:
      - customize-qcow2:
          matrix:
            parameters:
              flavor:
                - ubuntu-18.04
                # ubuntu-20.04
                # ubuntu-21.10
                # fedora-34
                # fedora-35
                # centos-8
                # - "centos-9"
                # - "arch-latest"
              arch: [amd64, arm64]
            exclude:
              - flavor: arch-latest
                arch: arm64

      - cradle-qcow2:
          requires:
            - customize-qcow2
          matrix:
            parameters:
              flavor:
                - ubuntu-18.04
                # ubuntu-20.04
                # ubuntu-21.10
                # fedora-34
                # fedora-35
                # centos-8
                # - "centos-9"
                # - "arch-latest"
              arch: [amd64]
            exclude:
              - flavor: arch-latest
                arch: arm64

#################################################################################
# Reuseable Jobs
jobs:

  # Download & Prepare qcow2 image(s)
  customize-qcow2:
    parameters:
      flavor:
        type: string
      arch:
        type: string
    executor: << parameters.arch >>
    environment:
      FLAVOR: << parameters.flavor >>
      ARCH: << parameters.arch >>
    steps:
      - checkout
      - qcow2-prepare:
          flavor: << parameters.flavor >>
          arch: << parameters.arch >>
      - ops_notify_err

  # Containerize qcow2 image(s)
  cradle-qcow2:
    parameters:
      flavor:
        type: string
      arch:
        type: string
    executor: amd64
    environment:
      FLAVOR: << parameters.flavor >>
    steps:
      - checkout
      - qcow2-cradle:
          flavor: << parameters.flavor >>
          arch: << parameters.arch >>

#################################################################################
# Reuseable Commands
commands:

  qcow2-prepare:
    description: "Qcow2 Image: Download and Customize"
    parameters:
      flavor:
        type: string
      arch:
        type: string
    steps:
      - restore_cache:
          key: << parameters.flavor >>-<< parameters.arch >>

      - run:
          command: |
            set -x
            mkdir -p cache/${ARCH}
            # Write out sha256sum for cache key
            NAME=${FLAVOR%-*}
            VERSION=${FLAVOR##*-}
            SHA256SUM=$(jq -r .distributions.${NAME}.\"${VERSION}\".${ARCH}.sha256sum index.json)
            echo ${SHA256SUM} > cache/${ARCH}/${FLAVOR}.txt

      - run:
          no_output_timeout: 90m
          command: |
            set -x

            # Install Qcow2 Build Dependencies
            sudo apt-get update
            sudo apt-get install -y jq

            # Disable libvirtd layer 
            # Required to support edge cases for some distributions
            export LIBGUESTFS_BACKEND=direct

            NAME=${FLAVOR%-*}
            export VERSION=${FLAVOR##*-}

            export QCOW2_FILE=${FLAVOR}-${ARCH}.qcow2
            export QCOW2_TMPFILE=tmp.${FLAVOR}-${ARCH}.qcow2

            export BASE_URL=$(jq -r .distributions.${NAME}.\"${VERSION}\".${ARCH}.url index.json)
            export SHA256SUM=$(jq -r .distributions.${NAME}.\"${VERSION}\".${ARCH}.sha256sum index.json)
            export DOWNLOAD_FILE=$(jq -r .distributions.${NAME}.\"${VERSION}\".${ARCH}.image index.json)

            customize_image() {

              sudo apt-get install -y curl qemu-user libguestfs-tools qemu-user-static

              # Source OS build variables
              source preview/${NAME}/env.sh

              # Download qcow2
              curl --verbose \
                --output ${QCOW2_TMPFILE} \
                --location ${BASE_URL}/${DOWNLOAD_FILE}

              # Verify Checksum
              echo "${SHA256SUM} ${QCOW2_TMPFILE}" \
                | sha256sum --check --status \
                || echo "Invalid checksum: sha256sum check failed"

              # Grow disk size
              qemu-img resize ${QCOW2_TMPFILE} +20G;

              # Customize Disk Image
              sudo virt-sysprep \
                --verbose \
                --network \
                --add ${QCOW2_TMPFILE} \
                --enable ${VIRT_SYSPREP_OPERATIONS} \
                --commands-from-file preview/${NAME}/virt.sysprep

              # Log disk image info
              qemu-img info ${QCOW2_TMPFILE}

              # Sparsify
              sudo virt-sparsify \
                --verbose \
                --compress \
                ${QCOW2_TMPFILE} \
                ${QCOW2_FILE} \
              && sudo chown ${USER}:${USER} ${QCOW2_FILE} \
              && sudo rm ${QCOW2_TMPFILE} \

            }

            # Check for && confirm cached customized image present || If not present then customize and cache
            [[ ! -f ${QCOW2_FILE} ]] && customize_image || echo "Detected cached disk image ... continuing"

#     - run:
#         command: |
#           # Log final image stats
#           qemu-img info ${FLAVOR}-${ARCH}.qcow2;

      - save_cache:
          key: << parameters.flavor >>-<< parameters.arch >>
          paths:
            - << parameters.flavor >>-<< parameters.arch >>.qcow2

  qcow2-cradle:
    description: "Qcow2 Image: Download and Customize"
    parameters:
      flavor:
        type: string
      arch:
        type: string
    steps:
      - restore_cache:
          keys:
            - << parameters.flavor >>-amd64
            - << parameters.flavor >>-arm64

      - run:
          no_output_timeout: 90m
          command: |
            set -x

            # Install Dependencies
            . /etc/os-release
            sudo sh -c "echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"
            wget -nv https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_${VERSION_ID}/Release.key -O Release.key
            sudo apt-key add - < Release.key
            sudo apt-get update
            sudo apt-get install -y jq skopeo buildah

            NAME=${FLAVOR%-*}
            export VERSION=${FLAVOR##*-}

            export QCOW2_FILE_ARM64=${FLAVOR}-arm64.qcow2
            export QCOW2_FILE_AMD64=${FLAVOR}-amd64.qcow2

            export BASE_URL=$(jq -r .distributions.${NAME}.\"${VERSION}\".${ARCH}.url index.json)
            export SHA256SUM=$(jq -r .distributions.${NAME}.\"${VERSION}\".${ARCH}.sha256sum index.json)
            export DOWNLOAD_FILE=$(jq -r .distributions.${NAME}.\"${VERSION}\".${ARCH}.image index.json)

            cradle_image_amd64() {

              # Make rootfs for copy into container
              mkdir -p rootfs/amd64/disk

              # Log image stats for loading to cradle
              #qemu-img info ${QCOW2_FILE_AMD64}.qcow2 > rootfs/disk/image-info.log

              # Copy image to rootfs
              cp ${QCOW2_FILE_AMD64} rootfs/amd64/disk/

              # Source OS build variables
              source preview/${NAME}/env.sh

              # Cradle AMD64 Disk Image
              buildah bud --squash -f amd64.Containerfile \
                -t quay.io/containercraft/${FLAVOR}:${VERSION}-${ARCH} \
                -t docker.io/containercraft/${FLAVOR}:${VERSION}-${ARCH}
            }

            [[ -f ${QCOW2_FILE_AMD64} ]] && cradle_image_amd64 || echo "Cradle task for AMD64 image ... qcow2 file not found .. Aborting!"

  # CMD: Slack Notify if ERR
  ops_notify_err:
    description: Alert Ops if Abort Failures Occur
    steps:
      - slack/notify:
          event: fail
          channel: ops-kargo
          template: basic_fail_1

  # CMD: Execute Docker Buildx
  buildx:
    description: "Runner: Execute Docker Buildx"
    parameters:
      bake_file:
        type: string
        default: bake.hcl
      target:
        type: string
      << : *platform_parameter
    steps:
      - run:
          command: |
            docker buildx bake \
              -f << parameters.bake_file >> \
              --progress plain \
              --set *.platform=linux/<< parameters.platform >> \
              << parameters.executor >>

  # CMD: Configure Docker BuildX
  enable_buildx:
    description: "Runner: Configure Docker Buildx Environment"
    parameters:
      buildkit_version:
        type: string
        default: latest
    steps:
      - run:
          command: docker run --privileged --rm tonistiigi/binfmt --install all
      - run:
          command: docker buildx ls | grep "build-<< parameters.buildkit_version >>"
      - run:
          command: echo ${DOCKERHUB_PASSWORD} | docker login -u ${DOCKERHUB_USERNAME} --password-stdin
      - ops_notify_err

#################################################################################
# Workflow Runner Instances
executors:

  # ARM64 Runner
  arm64:
    machine:
      enabled: true
      image: ubuntu-2004:202111-01
    environment:
      DOCKER_CLI_EXPERIMENTAL: enabled
    resource_class: arm.large

  # AMD64 Runner
  amd64:
    machine:
      enabled: true
      image: ubuntu-2004:202111-01
    environment:
      DOCKER_CLI_EXPERIMENTAL: enabled
    resource_class: large
