version: '2.1'
orbs:
  slack: circleci/slack@4.5.0

aliases:
  - &platform_parameter
      platform:
        type: enum
        enum: ["amd64", "arm64"]
        default: amd64

#################################################################################
# Job Scheduler
workflows:
  build-and-cache:
    jobs:
      - qcow2:
          name: bake-arm64
          target: ubuntu
          platform: arm64
          executor: arm64

#################################################################################
# Reuseable Jobs
jobs:
  qcow2:
    parameters:
      target:
        type: string
      << : *platform_parameter
      executor:
        type: executor
        default: amd64
    executor: << parameters.executor >>
    environment:
      FLAVOR: ubuntu
      VERSION: "18.04"
      RELEASE: "bionic"
    steps:
      - checkout
      - prepare
      - cache_qcow2
      - ops_notify_err

#################################################################################
# Reuseable Commands
commands:

  # CMD: Slack Notify if ERR
  ops_notify_err:
    description: "Alert Ops if Abort Failures Occur"
    steps:
      - slack/notify:
          event: fail
          channel: ops-kargo
          template: basic_fail_1

  # CMD: Qcow2 Image: Load from Cache || Download & Cache
  cache_qcow2:
    description: "Qcow2 Image: Load from Cache || Download & Cache"
    steps:
      - restore_cache:
          key: qcow2-ubuntu-bionic-arm64-tmp
          #key: qcow2-ubuntu-bionic-arm64-tmp-{{ checksum "preview/ubuntu/sha256sum.arm64.txt" }}

      - run:
          command: |
            [[ -f cache/arm64/tmp.ubuntu-18.04-arm64.qcow2 ]]  || 
            [[ ! -f cache/arm64/tmp.ubuntu-18.04-arm64.qcow2 ]]  \
              && curl --output ${FLAVOR}-${VERSION}-${ARCH}.qcow2 -L https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-${ARCH}.img \
              || circleci step halt

      - run:
          command: |
            # Download qcow2 from origin

            # Grow disk size
            qemu-img resize ${FLAVOR}-${VERSION}-${ARCH}.qcow2 +20G;

            # Basic sysprep
            sudo virt-sysprep --verbose --add ${FLAVOR}-${VERSION}-${ARCH}.qcow2 --network --update \
              --enable user-account,logfiles,customize,bash-history,net-hostname,net-hwaddr,machine-id,dhcp-server-state,dhcp-client-state,yum-uuid,udev-persistent-net,tmp-files,smolt-uuid,rpm-db,package-manager-cache \
              --run-command apt-get autoremove -y \
              --run-command apt-get purge -y;

            # Sparsify
            sudo virt-sparsify --verbose --compress --convert qcow2 ${FLAVOR}-${VERSION}-${ARCH}.qcow2 cache/${ARM}/tmp.${FLAVOR}-${VERSION}-${ARCH}.qcow2 \
              && rm ${FLAVOR}-${VERSION}-${ARCH}.qcow2

      - run:
          command: |
            # Log image stats
            qemu-img info cache/${ARCH}/tmp.${FLAVOR}-${VERSION}-${ARCH}.qcow2;

      - ops_notify_err
      - save_cache:
          key: qcow2-ubuntu-bionic-arm64-tmp
          #key: qcow2-ubuntu-bionic-arm64-tmp-{{ checksum "preview/ubuntu/sha256sum.arm64.txt" }}
          paths:
            - cache/arm64/tmp.ubuntu-18.04-arm64.qcow2

  # CMD: Qcow2 Image: Load from Cache || Download & Cache
  prepare_qcow2:
    description: "Qcow2 Image: Customize"
    steps:
      - restore_cache:
          key: qcow2-ubuntu-bionic-arm64-tmp
          key: qcow2-ubuntu-bionic-arm64-ccio
          #key: qcow2-ubuntu-bionic-arm64-ccio-{{ checksum "preview/ubuntu/sha256sum.arm64.txt" }}

      - run:
          command: |
            [[ ! -f cache/arm64/tmp.ubuntu-18.04-arm64.qcow2 ]] || circleci step halt

      - run:
          command: |
            # Verify qcow2 image
            qemu-img info cache/${ARCH}/tmp.${FLAVOR}-${VERSION}-${ARCH}.qcow2;

            # Sysprep customize
            sudo virt-sysprep --verbose --add tmp.${FLAVOR}-${VERSION}-${ARCH}.qcow2 --network --update \
              --enable user-account,logfiles,customize,bash-history,net-hostname,net-hwaddr,machine-id,dhcp-server-state,dhcp-client-state,yum-uuid,udev-persistent-net,tmp-files,smolt-uuid,rpm-db,package-manager-cache \
              --install screenfetch,python3,tmux,git,vim,net-tools,cloud-init,cloud-initramfs-growroot,qemu-guest-agent \
              --run-command apt-get autoremove -y \
              --run-command apt-get purge -y;

            # Sparsify
            sudo virt-sparsify --verbose --compress tmp.${FLAVOR}-${VERSION}-${ARCH}.qcow2 cache/arm64/${FLAVOR}-${VERSION}-${ARCH}.qcow2

      - run:
          command: |
            # Log image stats
            qemu-img info cache/${ARCH}/${FLAVOR}-${VERSION}-${ARCH}.qcow2;

      - save_cache:
          key: qcow2-ubuntu-bionic-arm64-ccio
          #key: qcow2-ubuntu-bionic-arm64-ccio-{{ checksum "preview/ubuntu/sha256sum.arm64.txt" }}
          paths:
            - cache/arm64/ubuntu-18.04-arm64.qcow2

  # CMD: Execute Docker Buildx
  buildx:
    description: "Runner: Execute Docker Buildx"
    parameters:
      bake_file:
        type: string
        default: bake.hcl
      target:
        type: string
      << : *platform_parameter
    steps:
      - run:
          command: |
            docker buildx bake \
              -f << parameters.bake_file >> \
              --progress plain \
              --set *.platform=linux/<< parameters.platform >> \
              << parameters.target >>

  # CMD: Configure Docker BuildX
  enable_buildx:
    description: "Runner: Configure Docker Buildx Environment"
    parameters:
      buildkit_version:
        type: string
        default: v0.9.3
    steps:
      - run:
          command: 'docker run --privileged --rm tonistiigi/binfmt --install all'
      - run:
          command: 'docker buildx ls | grep "build-<< parameters.buildkit_version >>"'
      - ops_notify_err

  # CMD: Prepare Host Build Dependencies
  prepare:
    description: "Runner: Host Preparedness"
    steps:
      - run:
          command: "sudo apt-get update && sudo apt-get install -y jq curl qemu-user libguestfs-tools qemu-user-static"
      - run:
          command: "echo ${DOCKERHUB_PASSWORD} | docker login -u ${DOCKERHUB_USERNAME} --password-stdin"

#################################################################################
# Workflow Runner Instances
executors:

  # ARM64 Runner
  arm64:
    machine:
      enabled: true
      image: ubuntu-2004:202111-01
    environment:
      ARCH: arm64
      DOCKER_CLI_EXPERIMENTAL: enabled
    resource_class: arm.large

  # AMD64 Runner
  amd64:
    machine:
      enabled: true
      image: ubuntu-2004:202111-01
    environment:
      ARCH: amd64
      DOCKER_CLI_EXPERIMENTAL: enabled
    resource_class: large