version: '2.1'
orbs:
  slack: circleci/slack@4.5.0

aliases:
  - &platform_parameter
      platform:
        type: enum
        enum: [amd64, arm64]
        default: amd64

#################################################################################
# Job Scheduler
workflows:
  build-and-cache:
    jobs:
      - customize-qcow2:
          matrix:
            parameters:
              flavor: [ubuntu]
              arch: [amd64, arm64]
              version: ["18.04", "20.04"]

#################################################################################
# Reuseable Jobs
jobs:
  customize-qcow2:
    parameters:
      flavor:
        type: string
      arch:
        type: string
      version:
        type: string
    executor: << parameters.arch >>
    environment:
      FLAVOR: << parameters.flavor >>
      ARCH: << parameters.arch >>
      VERSION: << parameters.version >>
    steps:
      - checkout
      - prepare
      - cache_qcow2:
          flavor: << parameters.flavor >>
          arch: << parameters.arch >>
          version: << parameters.version >>
      - prepare_qcow2:
          flavor: << parameters.flavor >>
          arch: << parameters.arch >>
          version: << parameters.version >>
      - ops_notify_err

#################################################################################
# Reuseable Commands
commands:

  # CMD: Slack Notify if ERR
  ops_notify_err:
    description: Alert Ops if Abort Failures Occur
    steps:
      - slack/notify:
          event: fail
          channel: ops-kargo
          template: basic_fail_1

  # CMD: Qcow2 Image: Load from Cache || Download & Cache
  cache_qcow2:
    description: "Qcow2 Image: Load from Cache || Download & Cache"
    parameters:
      flavor:
        type: string
      arch:
        type: string
      version:
        type: string
    steps:
      - restore_cache:
          key: qcow2-<< parameters.flavor >>-<< parameters.version >>-<< parameters.arch >>-tmp-{{ checksum "preview/<< parameters.flavor >>/sha256sum.<< parameters.version>>-<< parameters.arch >>.txt" }}

      - run:
          command: |
            run_cache_image () {

              # Source OS specific vars
              source preview/${FLAVOR}/env.sh

              # Download qcow2
              curl \
                --output ${FLAVOR}-${VERSION}-${ARCH}.qcow2 \
                --location $(jq -r .distributions.${FLAVOR}.\"${VERSION}\".${ARCH}.url index.json)

              SHA256SUM=$(jq -r .distributions.${FLAVOR}.\"${VERSION}\".${ARCH}.sha256sum index.json)
              echo "${SHA256SUM} ${FLAVOR}-${VERSION}-${ARCH}.qcow2"  | sha256sum --check --status

              # Grow disk size
              qemu-img resize ${FLAVOR}-${VERSION}-${ARCH}.qcow2 +20G;

              # Basic sysprep
              sudo virt-sysprep \
                --verbose \
                --add ${FLAVOR}-${VERSION}-${ARCH}.qcow2 \
                --network \
                --update \
                --enable ${VIRT_SYSPREP_OPERATIONS} \
                --run-command 'apt-get autoremove -y' \
                --run-command 'apt-get purge -y';

              # Sparsify
              sudo virt-sparsify \
                --verbose \
                --compress \
                --convert qcow2 ${FLAVOR}-${VERSION}-${ARCH}.qcow2 \
                cache/${ARCH}/tmp.${FLAVOR}-${VERSION}-${ARCH}.qcow2 \
              && rm ${FLAVOR}-${VERSION}-${ARCH}.qcow2
            }

            # Check for && confirm cached image present || If not present then download, prepare, and cache
            [[ ! -f cache/${ARCH}/tmp.${FLAVOR}-${VERSION}-${ARCH}.qcow2 ]] && run_cache_image || echo "Detected cached disk image ... continuing"

      - run:
          command: |
            # Log tmp image stats
            qemu-img info cache/${ARCH}/tmp.${FLAVOR}-${VERSION}-${ARCH}.qcow2;

      - ops_notify_err
      - save_cache:
          key: qcow2-<< parameters.flavor >>-<< parameters.version >>-<< parameters.arch >>-tmp-{{ checksum "preview/<< parameters.flavor >>/sha256sum.<< parameters.version>>-<< parameters.arch >>.txt" }}
          paths:
            - cache/<< parameters.arch >>/tmp.<< parameters.flavor >>-<< parameters.version >>-<< parameters.arch >>.qcow2

  # CMD: Qcow2 Image: Load from Cache || Download & Cache
  prepare_qcow2:
    description: "Qcow2 Image: Customize"
    parameters:
      flavor:
        type: string
      arch:
        type: string
      version:
        type: string
    steps:
      - restore_cache:
          key: qcow2-<< parameters.flavor >>-<< parameters.version >>-<< parameters.arch >>-ccio-{{ checksum "preview/<< parameters.flavor >>/sha256sum.<< parameters.version >>-<< parameters.arch >>.txt" }}

      - run:
          no_output_timeout: 60m
          command: |
            run_cache_customize () {

              # Verify qcow2 image
              qemu-img info cache/${ARCH}/tmp.${FLAVOR}-${VERSION}-${ARCH}.qcow2;

              # Sysprep customize
              sudo virt-sysprep \
                --verbose \
                --add cache/${ARCH}/tmp.${FLAVOR}-${VERSION}-${ARCH}.qcow2 \
                --network \
                --update \
                --enable user-account,logfiles,customize,bash-history,net-hostname,net-hwaddr,machine-id,dhcp-server-state,dhcp-client-state,yum-uuid,udev-persistent-net,tmp-files,smolt-uuid,rpm-db,package-manager-cache \
                --install screenfetch,python3,tmux,git,vim,net-tools,cloud-init,cloud-initramfs-growroot,qemu-guest-agent \
                --run-command 'apt-get autoremove -y' \
                --run-command 'apt-get purge -y';

              # Sparsify
              sudo virt-sparsify \
                --verbose \
                --compress \
                cache/${ARCH}/tmp.${FLAVOR}-${VERSION}-${ARCH}.qcow2 \
                cache/${ARCH}/${FLAVOR}-${VERSION}-${ARCH}.qcow2
            }

            # Check for && confirm cached customized image present || If not present then customize and cache
            [[ ! -f cache/${ARCH}/${FLAVOR}-${VERSION}-${ARCH}.qcow2 ]] && run_cache_customize || echo "Detected cached disk image ... continuing"

      - run:
          command: |
            # Log final image stats
            qemu-img info cache/${ARCH}/${FLAVOR}-${VERSION}-${ARCH}.qcow2;

      - save_cache:
          key: qcow2-ubuntu-bionic-<< parameters.arch >>-ccio-{{ checksum "preview/ubuntu/sha256sum.<< parameters.version >>-<< parameters.arch >>.txt" }}
          paths:
            - cache/<< parameters.arch >>/<< parameters.flavor >>-<< parameters.version >>-<< parameters.arch >>.qcow2

  # CMD: Execute Docker Buildx
  buildx:
    description: "Runner: Execute Docker Buildx"
    parameters:
      bake_file:
        type: string
        default: bake.hcl
      target:
        type: string
      << : *platform_parameter
    steps:
      - run:
          command: |
            docker buildx bake \
              -f << parameters.bake_file >> \
              --progress plain \
              --set *.platform=linux/<< parameters.platform >> \
              << parameters.executor >>

  # CMD: Configure Docker BuildX
  enable_buildx:
    description: "Runner: Configure Docker Buildx Environment"
    parameters:
      buildkit_version:
        type: string
        default: latest
    steps:
      - run:
          command: docker run --privileged --rm tonistiigi/binfmt --install all
      - run:
          command: docker buildx ls | grep "build-<< parameters.buildkit_version >>"
      - run:
          command: echo ${DOCKERHUB_PASSWORD} | docker login -u ${DOCKERHUB_USERNAME} --password-stdin
      - ops_notify_err

  prepare:
    description: "Runner: Install Prerequisites"
    steps:
      - run:
          command: sudo apt-get update && sudo apt-get install -y jq curl qemu-user libguestfs-tools qemu-user-static

#################################################################################
# Workflow Runner Instances
executors:

  # ARM64 Runner
  arm64:
    machine:
      enabled: true
      image: ubuntu-2004:202111-01
    environment:
      DOCKER_CLI_EXPERIMENTAL: enabled
    resource_class: arm.large

  # AMD64 Runner
  amd64:
    machine:
      enabled: true
      image: ubuntu-2004:202111-01
    environment:
      DOCKER_CLI_EXPERIMENTAL: enabled
    resource_class: large
