FROM quay.io/containercraft/ubi:base
USER root

ARG TARGETARCH
ARG FLAVOR=${FLAVOR}
ARG VERSION=${VERSION}
ARG PKG_LIST=${PKG_LIST}
ENV PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
WORKDIR /disk