# kind create cluster --config kind/config.yaml

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kmi-test
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
nodes:
  - role: control-plane
    image: kindest/node:v1.23.3
  - role: worker
    image: kindest/node:v1.23.3
    extraPortMappings:
    - containerPort: 30950
      hostPort: 30950
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: test=kmi
