name: Update Image Index
on:
  schedule:
    - cron: '0 0 * * *'
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2.4.0

      - name: Find and Update latest Images
        run: bash hack/update.sh

      - name: Push Updates
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git stage -A
          git commit -m "auto update image index" --all 2>&1 || true
          git push origin ccio
