name: End to End KMI Test
on:
  workflow_dispatch:
    inputs:
      flavor:
        description: "Image Flavor to test"
        required: true

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Validate Flavor is configured for testing
      run: |
        set -ex
        file .github/workflows/kind/${{ github.event.inputs.flavor }}.yml

    - name: Prepare Node
      run: |
        docker volume create worker1-containerd
        docker volume create control1-containerd

    - name: Create kind cluster QuboCI
      uses: helm/kind-action@v1.2.0
      with:
        cluster_name: kmi-test
        config: .github/workflows/kind/config.yml

    - name: Prepare Cluster
      run: |
        set -x
        kubectl cluster-info
        kubectl get storageclass standard
        kubectl get nodes -oyaml | grep 'test:' && echo "detected node label 'kmi=test'"
        ls $HOME/.ssh/id_rsa || ssh-keygen -t rsa -N "" -f $HOME/.ssh/id_rsa
        kubectl create secret generic kargo-sshpubkey-kc2user --from-file=key1=$HOME/.ssh/id_rsa.pub

    - name: Test Cluster
      run: |
        set -x
        source ./hack/test.sh
