name: End to End KMI Test and Promotion
on:
  workflow_dispatch:
    inputs:
      flavor:
        description: "Image Flavor to test (ex. ubuntu-18.04)"
        required: true

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    env:
      FLAVOR: ${{ github.event.inputs.flavor }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install bats
        run: apt-get install -y bats

      - name: Prepare Node
        run: |
          docker volume create worker1-containerd
          docker volume create control1-containerd

      - name: Create kind cluster QuboCI
        uses: helm/kind-action@v1.2.0
        with:
          cluster_name: kmi-test
          config: .github/workflows/kind/config.yml

      - name: Test ${{ github.event.inputs.flavor }}
        run: |
          bats tests/test.bats --show-output-of-passing-tests --timing --verbose-run

      - name: Archive test logs
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: ${{ github.event.inputs.flavor }}-logs
          path: |
            ${{ github.workspace }}/*.txt

  promote-image:
    runs-on: ubuntu-latest
    needs: e2e-test
    permissions:
      id-token: write
    env:
      FLAVOR: ${{ github.event.inputs.flavor }}
      COSIGN_EXPERIMENTAL: 1
    steps:
      - name: Setup cosign
        uses: sigstore/cosign-installer@main

      - name: Login Docker Hub
        uses: redhat-actions/podman-login@v1
        with:
          logout: false
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}

      - name: Login Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          logout: false
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}

#      - name: Login Quay.io
#        uses: docker/login-action@v1.10.0
#        with:
#          logout: false
#          registry: quay.io
#          username: ${{ secrets.QUAY_USER }}
#          password: ${{ secrets.QUAY_PASSWD }}

      - name: Copy the manifest to product tag
        run: |
          skopeo copy --all \
            docker://docker.io/containercraft/${FLAVOR//-/:}-dev \
            docker://docker.io/containercraft/${FLAVOR//-/:}

      - name: Sign the image
        run: cosign sign --recursive docker.io/containercraft/${FLAVOR//-/:}

      - name: Verify the image
        run: cosign verify docker.io/containercraft/${FLAVOR//-/:}
