name: Update Image Index
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Find and Update latest Images
        run: bash hack/update.sh

      - name: Push Updates
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "auto update image hashes" --all 2>&1 || true
          git push origin HEAD
